---
- name: Main playbook
  hosts: localhost
  connection: local

  pre_tasks:
    - name: Provide operational instructions
      ansible.builtin.debug:
        msg: Following are a set of questions to help you set up your environment. Enter the word from the option. Options can be combined with space separation.

  tasks:
    - name: Prompt user
      when: (lookup('env', 'DOTFILE_INSTALL_ALL') | default('false')) != 'true'
      block:
        - name: Select shell
          ansible.builtin.pause:
            prompt: |
              Choose your shell:
              1) zsh - Zsh
              2) fish - Fish
          register: shell

        - name: Select terminal
          ansible.builtin.pause:
            prompt: |
              Choose your terminal:
              1) kitty - Kitty
              2) ghostty - Ghostty
          register: terminal
            
        - name: Select editor
          ansible.builtin.pause:
            prompt: |
              Choose your editor:
              1) helix - Helix
              2) nvim - Neovim
              3) emacs - Emacs
              4) intellij - IntelliJ IDEA
              5) vscode - Visual Studio Code
              6) astudio - Android Studio
          register: editor

        - name: Select SDK
          ansible.builtin.pause:
            prompt: |
              Choose your SDK:
              1) java - Java (OpenJDK, Maven, Gradle, jdtls)
              2) py - Python (Python 3, uv, pyrefly)
              3) js - JavaScript (Node.js, Typescript)
              4) rust - Rust (rustup, Cargo)
              5) gleam - Gleam
              6) go - Go
              7) clj - Clojure
              8) rkt - Racket
              9) haskell - Haskell
              10) dart - Dart (Flutter)
              11) dotnet - C#/F# (.NET SDK)
              12) ps - PureScript
              13) julia - Julia
              14) kotlin - Kotlin
              15) dlang - D
              16) php - PHP (Tomcat)
              17) scala - Scala
              18) elm - Elm
              19) ocaml - OCaml
              20) apl - APL
              21) zig - Zig
              22) nim - Nim
              23) crystal - Crystal
              24) lua - Lua
              25) raku - Raku
              26) swift - Swift
          register: sdk

        - name: Select dev tools
          ansible.builtin.pause:
            prompt: |
              Choose your development tools:
              1) docker - Docker
              2) kubectl - Kubernetes CLI
              3) helm - Helm
              4) opentofu - Terraform/OpenTofu
              5) pulumi - Pulumi
          register: tools

        - name: Start tasks
          ansible.builtin.include_tasks: "{{ item }}"
          loop:
            - "../tasks/shell.yml"
            - "../tasks/terminal.yml"
            - "../tasks/editor.yml"
            - "../tasks/sdk.yml"

