---
- name: Set variable
  set_fact:
    install_all: "{{ lookup('env', 'DOTFILE_INSTALL_ALL') | default('false') == 'true' }}"

- name: Debug install_all variable
  ansible.builtin.debug:
    msg: "SDK {{ install_all }}"

- name: Setup PHP
  block:
    - name: Install Tomcat server
      ansible.builtin.include_role:
        name: geerlingguy.php
  become: true
  when: ('php' in sdk.user_input) or install_all

- name: Setup Python
  block:
    - name: Install Python 3
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - pyrefly
        - uv
  when: ('py' in sdk.user_input) or install_all
