name: Lint ansible files

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          setup_python: "true"
          working_directory: "ansible/"
          # requirements_file: ""
