name: Test dotfiles using Docker

on:
  push:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu:24.04
          - fedora:42
          - archlinux:latest
          - opensuse/tumbleweed:latest
    container: ${{ matrix.distro }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          chmod +x ./scripts/install-ansible.sh
          ./scripts/install-ansible.sh

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: main.yml
          directory: ./ansible/playbooks
          # requirements: galaxy-requirements.yml
          options: |
            --extra-vars DOTFILE_INSTALL_ALL=true
